stages:
  - check
  - build

variables:
  GIT_CLONE_PATH: /builds
  LOGFILE: /builds/logs/kupferbootstrap.log
  ARCH: aarch64

default:
  image: registry.gitlab.com/kupfer/kupferbootstrap:dev
  before_script:
    - mkdir -p /kupfer/{pkgbuilds,packages,prebuilts} /root/.cache/kupfer "$(dirname "$LOGFILE")"
    - mount --bind /kupfer/{packages,prebuilts}
    - for dir in /pkgbuilds /prebuilts; do mkdir -p "$dir" && mount --bind /kupfer"$dir" "$dir"; done
    - mount --bind /kupfer /root/.cache/kupfer
    - cd /kupfer
    - cp -a /builds/. ./pkgbuilds/
    - kupferbootstrap config init -N
  artifacts: &logartifacts
    name: logs
    paths:
      - "$LOGFILE"
    expire_in: 30 days
    when: always

check_formatting:
  stage: check
  tags:
    - packages
  script:
    - script -e --log-out "$LOGFILE" -c 'kupferbootstrap packages check all'

.build:
  stage: build
  only: &build_only
    refs:
      - branches
    changes:
      - '[a-z]*/*/*'
  variables:
    buildarch: "aarch64"
  script: &build_script
    - cd /kupfer
    - git clone --depth=1 -b "$REPOBRANCH" https://gitlab.com/kupfer/packages/prebuilts.git packages
    - script -e --log-out "$LOGFILE" -c 'kupferbootstrap packages clean --force'
    - script -e --log-out "$LOGFILE" -c "kupferbootstrap packages build --arch '$buildarch' all"
    - 'cd ./pkgbuilds && ./.gitlab/check_modified.sh'
  tags:
    - packages

build_packages:
  variables:
    REPOBRANCH: dev
  extends: .build
  except:
    - main@kupfer/packages/pkgbuilds
    - dev@kupfer/packages/pkgbuilds
  after_script:
    - cd /kupfer/packages
    - for p in $(git ls-files --others --exclude-standard) ; do echo "copying $p" ; install -Dm644 "$p" "$GIT_CLONE_PATH/packages/$p" ; done
  artifacts:
    <<: *logartifacts
    name: artifacts
    paths:
      - "$LOGFILE"
      - "packages/*/*/*.*"

push_packages:
  variables:
    REPOBRANCH: "$CI_COMMIT_BRANCH"
  extends: .build
  tags:
    - packages
  only:
    <<: *build_only
    refs:
      - main@kupfer/packages/pkgbuilds
      - dev@kupfer/packages/pkgbuilds
  script:
    - *build_script
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - cd ~/.ssh
    - eval $(ssh-agent -s)
    - echo "$SSH_KEY" > id_rsa.base64
    - openssl enc -d -base64 -A -in id_rsa.base64 -out id_rsa
    - chmod 600 id_rsa
    - ssh-add id_rsa
    - ssh-keyscan -t rsa gitlab.com >> ~/.ssh/known_hosts
    - git config --global user.email "kupfer@kupfer.cu"
    - git config --global user.name "Kupfer Bot"
    - cd /kupfer/packages
    - git remote set-url origin git@gitlab.com:kupfer/packages/prebuilts.git
    - (git ls-files --others --exclude-standard | grep '\.pkg\.' | xargs -r dirname | xargs -r git add) || echo "Apparently no packages to upload."
    -
      (if ! git commit -m "$("$GIT_CLONE_PATH"/.gitlab/generate-commit-message.sh)"; then
        echo 'git commit failed! checking prebuilts.git commit history' >&2 &&
        if ! [[ -n "$CI_COMMIT_SHA" ]]; then
          echo 'No pkgbuilds.git commit sha found!' >&2 &&
          exit 1 ;
        fi ;
        last_modified="$(cd "$GIT_CLONE_PATH" && git log --format=oneline [a-z]* | head -n1 | cut -d' ' -f1)" &&
        for commit in "$CI_COMMIT_SHA" "$last_modified" ; do
          [[ -n "$commit" ]] || continue ;
          if (git log --format=oneline | grep -q "$commit") ; then
            echo -e "Commit found. Seems like prebuilts for $commit were already built.\nNot erroring." >&2 &&
            exit 0 ;
          fi ;
          echo "Commit $commit not found in log.">&2 ;
        done ;
        echo "Commit hashes not found in prebuilts.git log. Erroring out.">&2 &&
        exit 1 ;
      fi) &&
      (git push || git push) # try pushing twice since pushing occasionally fails
